timeout: 10m
format: 'sarif'
output: 'trivy-results.sarif'
dependency-tree: true
list-all-pkgs: true
exit-code: 1
severity:
  - HIGH
  - CRITICAL
scan:
  skip-dirs:
    .settings
    .m2
    docs
    infrastructure
    target
    vro-types

  scanners:
    - vuln
    - secret
vulnerability:
  type:
    - os
    - library
  ignore-unfixed: true
