/*-
 * #%L
 * vrotsc
 * %%
 * Copyright (C) 2023 - 2024 VMware
 * %%
 * Build Tools for VMware Aria
 * Copyright 2023 VMware, Inc.
 *
 * This product is licensed to you under the BSD-2 license (the "License"). You may not use this product except in compliance with the BSD-2 License.
 *
 * This product may include a number of subcomponents with separate copyright notices and license terms. Your use of these subcomponents is subject to the terms and conditions of the subcomponent's license, as noted in the LICENSE file.
 * #L%
 */
import * as assert from "assert";
import { printElementInfo } from "../compiler/elementInfo";

describe("printElementInfo", () => {

    it("produces valid XML structure with header and properties tags", () => {
        const result = printElementInfo({ id: "abc123" });
        assert.ok(result.includes(`<?xml version="1.0" encoding="utf-8" standalone="no"?>`));
        assert.ok(result.includes(`<!DOCTYPE properties SYSTEM "http://java.sun.com/dtd/properties.dtd">`));
        assert.ok(result.includes(`<properties>`));
        assert.ok(result.includes(`</properties>`));
    });

    it("includes the vrotsc generator comment", () => {
        const result = printElementInfo({});
        assert.ok(result.includes(`<comment>Generated by vrotsc</comment>`));
    });

    it("renders a single key-value property as an entry element", () => {
        const result = printElementInfo({ name: "myWorkflow" });
        assert.ok(result.includes(`<entry key="name">myWorkflow</entry>`));
    });

    it("renders multiple properties as separate entry elements", () => {
        const result = printElementInfo({ id: "123", name: "test", version: "1.0.0" });
        assert.ok(result.includes(`<entry key="id">123</entry>`));
        assert.ok(result.includes(`<entry key="name">test</entry>`));
        assert.ok(result.includes(`<entry key="version">1.0.0</entry>`));
    });

    it("returns an empty properties block for an empty input object", () => {
        const result = printElementInfo({});
        assert.ok(result.includes(`<properties>`));
        assert.ok(result.includes(`</properties>`));
        assert.ok(!result.includes(`<entry`));
    });

    it("each line ends with a newline character", () => {
        const result = printElementInfo({ key: "value" });
        const lines = result.split("\n");
        assert.ok(lines.length > 1, "output should have multiple lines");
    });

    it("property value is placed between the entry tags", () => {
        const result = printElementInfo({ category: "com.vmware.pscoe" });
        assert.ok(result.includes(`<entry key="category">com.vmware.pscoe</entry>`));
    });
});
