---
# Example blueprints:
# blueprint:
#  - Volume
#  - Machine
# Example subscriptions:
# subscription:
#  - subscription 1
#  - subscription 2
#  - subscription 3
# Example vra workflow Catalog Item
# catalog-item:
#   - source__Sum two numbers
# Example vra workflow Content SOurce
# content-source:
#   - source
# Example Catalog Entitlement:
# catalog-entitlement
#  - content source entitlement 1
#  - content source entitlement 2
# Example Property Groups:
# property-group:
#  - property-group-1
# policy:
#   approval:
#     - policy name 1
#     - policy name 2
#   content-sharing:
#     - policy name 1
#     - policy name 2
#   day2-actions:
#     - policy name 1
#     - policy name 2
#   deployment-limit:
#     - policy name 1
#     - policy name 2
#   lease:
#     - policy name 1
#     - policy name 2
#   resource-quota:
#     - policy name 1
#     - policy name 2
# scenario:

blueprint:
  - Small VM
catalog-item: 
  - Orchestrator_Development__Add a REST host
content-source:
    - Orchestrator_Development
custom-resource:
  - CustomResource
policy:
  approval:
    - vra8-db-mssql Approval Policy
  content-sharing:
    - vra8-db-mssql Content Sharing Policy
  day2-actions:
    - vra8-db-mssql Day 2 Actions Policy
  deployment-limit:
    - vra8-db-mssql Deployment Limit Policy
  lease:
    - vra8-db-mssql Lease Policy
  resource-quota:
    - vra8-db-mssql Resource Quota Policy
property-group:
  - vra8_db_mssql_property_group
resource-action:
  - Cloud.vSphere.Machine__add_disk_to_vm
subscription:
  - vra8-db-mssql Subscription
catalog-entitlement: []
scenario: []
